language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - SYMFONY_VERSION='2.3.*' deps='no'
  - SYMFONY_VERSION='2.7.*' deps='no'
  - SYMFONY_VERSION='2.8.*' deps='no'

matrix:
    include:
      - php: 5.4
        env: SYMFONY_VERSION='2.3.*' deps='low'
      - php: 5.5
        env: SYMFONY_VERSION='3.0.*' deps='no'
      - php: 5.6
        env: SYMFONY_VERSION='3.0.*' deps='no'
      - php: 7
        env: SYMFONY_VERSION='3.0.*' deps='no'

    allow_failures:
        - php: hhvm

before_install:
  - travis_retry composer self-update

install:
    - composer require --no-update symfony/symfony=${SYMFONY_VERSION}
    - if [ "$deps" = "no" ]; then composer --prefer-source install; fi;
    - if [ "$deps" = "low" ]; then composer --prefer-source --prefer-lowest --prefer-stable update; fi;

script:
  - mkdir -p build
  - phpunit --colors -c phpunit.xml --coverage-text
