language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - nightly
  - hhvm

env:
  - PACKAGES='symfony/symfony=2.7.*' deps='no'
  - PACKAGES='symfony/symfony=2.8.*' deps='no'
  - PACKAGES='symfony/symfony=3.2.*' deps='no'
  - PACKAGES='symfony/symfony=~3.3@dev' deps='no'

matrix:
    include:
      - php: 5.4
        env: PACKAGES='symfony/symfony=2.7.*' deps='no'
      - php: 5.4
        env: PACKAGES='symfony/symfony=2.7.*' deps='low'

    allow_failures:
        - php: hhvm
        - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - composer require --no-update ${PACKAGES}
  - if [ "$deps" = "no" ]; then composer --prefer-source install; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-source --prefer-lowest --prefer-stable update; fi;

script:
  - mkdir -p build
  - vendor/bin/phpunit --colors
